### ISSUE TITLE
Edges tests do not run due to Sauce Labs API change

### ISSUE THREAD

**Issue by feross** [airtap/airtap#155]
I believe the [Sauce Labs API endpoint](https://saucelabs.com/rest/v1/info/platforms/webdriver) that we use in `airtap --list-browsers` used to return `microsoftedge` as the `api_name` for Microsoft Edge. However it appears they are now returning `MicrosoftEdge` instead.

This means that any `.airtap.yml` file that specifies the lowercase variant will silently skip testing Microsoft Edge now...

Example file:

```yml
sauce_connect: true
loopback: airtap.local
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: latest
```

I have about 25 repos that now aren't testing Edge anymore 🤯

Should we make the matching be case-insensitive?
