### ISSUE TITLE
Random idea: move out "local mode"

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#172]
Far from a complete plan, here's how it could work:

- Specify browsers with [`browserlists`](https://github.com/browserslist/browserslist)
- Have `airtap` merge it with browsers specified in `.airtap.yml` for backwards compat
- Reduce `airtap` scope to be exclusively for Sauce Labs tests
- Write a new CLI module to replace `airtap --local`
  - Use `airtap` API to start a server with instrumentation
  - Take browserslist
  - Launch browsers with [`just-launch`](https://github.com/juliangruber/just-launch) by @juliangruber
  - Each browser opens `http://localhost:<port>/airtap`
  - On Linux and OSX, it would use default browsers (i.e. `which firefox`)
  - On Windows, it can use version info from [`win-detect-browsers`](https://github.com/vweevers/win-detect-browsers) to support `browserslist` ranges! As an example, [`windows-firefox`](https://github.com/vweevers/windows-firefox) already allows you to select a binary by release channel or version.
  - `just-launch` supports Electron, so maybe we can remove Electron from `airtap`.
  - It would be awesome to have livereload (in all open browsers).

**Comment by KayleePop** [comment]
Could call the local cli `groundtap` 😝

**Comment by juliangruber** [comment]
This sounds exciting!

**Comment by vweevers** [comment]
Plans changed and sadly those plans did not include a module that would be deserving of the name `groundtap`. But! With the upcoming Airtap 4 (`npm i airtap/airtap` at the time of writing) you can do the following things:

**Run tests on default browser**

```
$ airtap test.js
```

**Run tests concurrently on locally installed Chrome, Chromium, Firefox, IE, Edge, Brave, Opera or Safari**

Create a `.airtap.yml`:

```yaml
providers:
  - airtap-system

browsers:
  - name: chrome
  - name: firefox
  - name: firefox
    version: dev
```

```
$ npm i airtap-system
$ airtap test.js
```

**Run tests on Playwright (headless Chromium, FF and WebKit)**

```yaml
providers:
  - airtap-playwright

browsers:
  - name: chromium
  - name: firefox
  - name: webkit
    options:
      headless: false
```

```
$ npm i airtap-playwright
$ airtap test.js
```

**Run tests on Electron**

```yaml
providers:
  - airtap-electron

browsers:
  - name: electron
    options:
      headless: false
```

```
$ npm i airtap-electron
$ airtap test.js
```

**Combine them and let Airtap find the best match**

```yaml
providers:
  - airtap-system
  - airtap-playwright
  - airtap-electron
  - airtap-default

browsers:
  - name: electron
  - name: chrome
  - name: firefox
    provider: airtap-playwright
  - name: default
```

```
$ airtap test.js
```

**Use different combinations for local usage and CI**

```yaml
providers:
  - airtap-sauce

browsers:
  - name: chrome
  - name: firefox

presets:
  local:
    providers:
      - airtap-system
```

```
$ airtap --preset local test.js
```

**Live reload on any of them**

```
$ airtap --live test.js
```

---

With that, I'm closing this. Not gonna do `browserslist` integration. Might reconsider `just-launch` later, I instead used `@httptoolkit/browser-launcher` under the assumption it was actively maintained and would have ironed out more kinks but it's not stable yet.
