### ISSUE TITLE
Saucelabs browsers cannot connect to airtap on local machine

### ISSUE THREAD

**Issue by t-mullen** [airtap/airtap#255]
Running tape tests with `airtap --local` works fine. I can run tests on SauceLabs when airtap is running on Travis - but this does not seem to work when running on SauceLabs locally.

Browsers launch on SauceLabs and attempt to load the correct airtap url, but timeout after failing to connect. It seems like this is a problem with the tunnel.

Is there additional configuration required not mentioned in the docs? (https://github.com/airtap/airtap/blob/master/doc/cloud-testing.md)

Airtap Version: 2.0.3
OS: OSX High Sierra 10.13.6
Browser: Any

```
sauce_connect: true
loopback: airtap.local # tried with and without
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: iphone
    version: latest
```
