### ISSUE TITLE
Using es6 modules with airtap

### ISSUE THREAD

**Issue by bmz1** [airtap/airtap#294]
Hello there!

I'd like to use airtap with es6 modules, however I couldn't find a way yet. 

I tried the following script: `"test": "airtap --local -r esm src/test/*.test.js"`
It looks like airtap ignores the esm flag. Could you please recommend a way to get it working?
Thanks

**Comment by vweevers** [comment]
A browserify transform or plugin, like babel or esmify, should do the trick. Unless you want to test real ESM in browsers, then I'm not sure.

**Comment by jimmywarting** [comment]
We also want to test real ESM in the browser

**Comment by vweevers** [comment]
I haven't used real ESM before, some guidance is welcome.

First thoughts: I suppose airtap would have to serve the user's input files as-is without bundling them, acting as a static file server. The [client](https://github.com/airtap/airtap/blob/master/client/index.js) could then load those files either by appending `<script type="module">` elements to the DOM, or through a dynamic [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports).

Currently we serve a bundle at `http://localhost:1234/airtap/test.js`. This URL will have to be dynamic and use a dedicated route, something like `http://localhost:1234/user/*`. We could have the airtap server send a list of entrypoint URLs to the client, over the websocket.

Which directory should we serve? For example given `test/*.mjs`. Do we serve `test/` or the complete working directory (including `node_modules`)? It's likely that tests will import e.g. `../src/foo.mjs`. So we'd serve files like so:

- `http://localhost:1234/user/test/foo-test.mjs` => `/cwd/test/foo-test.mjs`
- `http://localhost:1234/user/src/foo.mjs` => `/cwd/src/foo.mjs`

Sound good so far?

**Comment by jimmywarting** [comment]
There is also the possibility of using import maps for node_modules

**Comment by vweevers** [comment]
Are there any good (simple and unopinionated) npm packages to help us create import maps? Or (if there are other caveats besides import maps) a general solution for serving ESM files? I'm looking for small building blocks, rather than a full framework or bundler like snowpack.

**Comment by ThaUnknown** [comment]
seems like specifying 
```yml
browserify:
  - plugin: 'esmify'
```
inside .airtap.yml *mostly* fixes this except for type assertion, for browserify CLI doing `-t [ babelify --presets [@babel/preset-env] --plugins [@babel/plugin-syntax-import-assertions]]` does the job, but i have no fucking clue how to specify that for yml as it doesn't seem to accept args

**Comment by vweevers** [comment]
```yaml
browserify:
  - transform: babelify
    presets: ['@babel/preset-env']
    plugins: ['@babel/plugin-syntax-import-assertions']
```

**Comment by ThaUnknown** [comment]
> ```yaml
> browserify:
>   - transform: babelify
>     presets: ['@babel/preset-env']
>     plugins: ['@babel/plugin-syntax-import-assertions']
> ```

this doesn't seem to work for me, even tho it parses it

**Comment by ThaUnknown** [comment]
@vweevers `SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (2:0) while parsing`

**Comment by vweevers** [comment]
My example was just to show how to specify transform options. The complete configuration should also include esmify.

**Comment by ThaUnknown** [comment]
> My example was just to show how to specify transform options. The complete configuration should also include esmify.

for CLI browserify you don't need esmify when u specify babelify, anyways even if i add esmify as a plugin it just straight up ignores the transform:
![image](https://user-images.githubusercontent.com/6506529/202543097-a64821dc-f639-44b9-a5fb-3b85840b4f36.png)
code:
```yml
browserify:
  - plugin: 'esmify'
  - transform: babelify
    presets: ['@babel/preset-env']
    plugins: ['@babel/plugin-syntax-import-assertions']
```

**Comment by vweevers** [comment]
I see. OK, then I can't be of further assistance. You now know how to specify options in `airtap.yml`, so unless you have more questions about airtap specifically, you'll have to figure out the right combination of plugins and transforms yourself.

**Comment by ThaUnknown** [comment]
@vweevers this seems to be a bug with airtap, as running the cli command I listed above works fine, with only babelify

**Comment by ThaUnknown** [comment]
@vweevers welp, feel free to add this to the readme

To compile ESM tests and modules to your `.airtap.yml` add:
```yml
browserify:
  - options:
      dedupe: false
  - transform: babelify
    global: true
    presets: ['@babel/preset-env']
    plugins: ['@babel/plugin-syntax-import-assertions']
```
make sure that your root package.json does not have any `browserify` or `babel` fields!
