### ISSUE TITLE
No support for local option w/ providers?

### ISSUE THREAD

**Issue by jzombie** [airtap/airtap#322]
Is there a CLI option to test local browsers without having to change the .airtap.yml file to not connect to sauce?

I want to connect to sauce in CI/CD, but not locally.

**Comment by vweevers** [comment]
If you're referring to the `--local` option that airtap 3 had, that's covered in [UPGRADING.md](https://github.com/airtap/airtap/blob/master/UPGRADING.md#replaced---electron-and---local).

**Comment by jzombie** [comment]
Ah, thank you.

`airtap test.js # runs chrome in sauce labs
airtap -p local test.js # runs local chrome`

---

By the way, I converted an existing project using this into TypeScript and was pleased with the ability to add plugins to browserify via options in airtap.  Works great.

**Comment by jzombie** [comment]
Same results even if I use the new CLI option.  I still have to modify the .airtap.yml file manually to make it not connect.

```
# sauce_connect: true
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  # FIXME: Safari on macOS via SauceLabs is currently (as of May 22, 2022) not
  # functional due to the dynamic hostname airtap.local not being applied
  # - name: safari
  #  version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
# providers:
#  - airtap-sauce
presets:
  local:
    browsers:
      - name: default
browserify:
  - plugin: tsify

```

**Comment by vweevers** [comment]
> to make it not connect

Connect to what? Not sure I understand.

**Comment by jzombie** [comment]
If I uncomment the sauce_connect / sauce providers, it tries to run the tests on Sauce Labs regardless of whether I want to use the local preset.

Is there a way to configure this to only connect to sauce if I'm not using the local preset?

**Comment by vweevers** [comment]
The `sauce_connect` option has been removed, so that's not what causing it. I think the problem is that your local preset is only overriding `browsers` (and not `providers`) and the only "global" provider is `airtap-sauce`, so airtap is asking the `airtap-sauce` provider to find a browser that has `name: default`.

Try this instead:

```yaml
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  # FIXME: Safari on macOS via SauceLabs is currently (as of May 22, 2022) not
  # functional due to the dynamic hostname airtap.local not being applied
  # - name: safari
  #  version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
providers:
  - airtap-sauce
presets:
  local:
    providers:
      - airtap-default # or airtap-system if you prefer
    browsers:
      - name: default
browserify:
  - plugin: tsify
```
